class DataAdapter: ...
class MongoAdapter(DataAdapter): ...
class TinyAdapter(DataAdapter): ...
class Collection: ...
class MongoCollection(Collection): ...
class TinyCollection(Collection): ...
